/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIew;

import javax.swing.table.DefaultTableModel;
import Model.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        this.setLocationRelativeTo(null);
        menuAtualizar.setEnabled(false);
        menuExcluir.setEnabled(false);
        menuVender.setEnabled(false);
        menuRelatorio.setEnabled(false);

        updateTable();
        if (Veiculo.getList().size() == 0 && VendaVeiculo.getListVendas().size() > 0) {
            menuRelatorio.setEnabled(true);
        }
    }

    public void habilitarBtn() {
        menuCadastrar.setEnabled(true);
        menuVender.setEnabled(false);
        menuAtualizar.setEnabled(false);
        menuExcluir.setEnabled(false);
        menuRelatorio.setEnabled(true);

    }

    public void desabilitarBtn() {
        menuCadastrar.setEnabled(false);
        menuVender.setEnabled(true);
        menuAtualizar.setEnabled(true);
        menuExcluir.setEnabled(true);
        menuRelatorio.setEnabled(false);

    }

    public void updateTable() {
        DefaultTableModel dtmTableVeiculo = (DefaultTableModel) tableVeiculos.getModel();
        dtmTableVeiculo.setRowCount(0);

        String tipoVeiculo = comboBoxListarVeiculos.getSelectedItem().toString(); //CARRO - MOTO - TODOS

        for (int i = 0; i < Veiculo.getList().size(); i++) {
            if (tipoVeiculo.equals("TODOS")
                    || (Veiculo.getList().get(i).getTipo().toString().equals(tipoVeiculo))) {
                habilitarBtn();
                dtmTableVeiculo.addRow(new Object[]{
                    
                    Veiculo.getList().get(i).getCodigo(),
                    Veiculo.getList().get(i).getTipo(),
                    Veiculo.getList().get(i).getMarca(),
                    Veiculo.getList().get(i).getModelo(),
                    Veiculo.getList().get(i).getAno(),
                    Veiculo.getList().get(i).getValor()
                });
            }
        }
        dtmTableVeiculo.fireTableDataChanged();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVeiculos = new javax.swing.JTable();
        comboBoxListarVeiculos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastrar = new javax.swing.JMenu();
        menuAtualizar = new javax.swing.JMenu();
        menuExcluir = new javax.swing.JMenu();
        menuVender = new javax.swing.JMenu();
        menuRelatorio = new javax.swing.JMenu();
        btnSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 30)); // NOI18N
        jLabel1.setText("Bem Vindo(a) a Locadora de Veículos");

        tableVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Veículo", "Marca", "Modelo", "Ano", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableVeiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableVeiculos);
        if (tableVeiculos.getColumnModel().getColumnCount() > 0) {
            tableVeiculos.getColumnModel().getColumn(0).setResizable(false);
            tableVeiculos.getColumnModel().getColumn(1).setResizable(false);
            tableVeiculos.getColumnModel().getColumn(2).setResizable(false);
            tableVeiculos.getColumnModel().getColumn(3).setResizable(false);
            tableVeiculos.getColumnModel().getColumn(4).setResizable(false);
        }

        comboBoxListarVeiculos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "CARRO", "MOTO" }));
        comboBoxListarVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxListarVeiculosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Deseja Listar :");

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jMenuBar1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuBar1.setMargin(new java.awt.Insets(20, 30, 10, 10));

        menuCadastrar.setText("Cadastrar Veículo");
        menuCadastrar.setMargin(new java.awt.Insets(3, 40, 3, 40));
        menuCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCadastrarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuCadastrar);

        menuAtualizar.setText("Atualizar Veículo");
        menuAtualizar.setMargin(new java.awt.Insets(3, 15, 3, 50));
        menuAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAtualizarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuAtualizar);

        menuExcluir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        menuExcluir.setText("Excluir Veículo");
        menuExcluir.setMargin(new java.awt.Insets(3, 45, 3, 50));
        menuExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuExcluirMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuExcluir);

        menuVender.setText("Vender Veículo");
        menuVender.setMargin(new java.awt.Insets(3, 45, 3, 30));
        menuVender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuVenderMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuVender);

        menuRelatorio.setText("Relatório");
        menuRelatorio.setMargin(new java.awt.Insets(3, 30, 3, 6));
        menuRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuRelatorioMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuRelatorio);

        btnSair.setBackground(new java.awt.Color(255, 51, 51));
        btnSair.setText("Sair");
        btnSair.setMargin(new java.awt.Insets(3, 40, 3, 20));
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxListarVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(285, 285, 285))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)))
                        .addGap(64, 64, 64))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxListarVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCadastrarMouseClicked
        if (tableVeiculos.getSelectedRow() > -1) {
            JOptionPane.showMessageDialog(rootPane, "Não é possível Cadastrar um novo veículo com linha selecionada.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        TelaCadastrar cadastro = new TelaCadastrar();
        cadastro.setVisible(true);
        dispose();
        desabilitarBtn();

    }//GEN-LAST:event_menuCadastrarMouseClicked

    private void menuAtualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAtualizarMouseClicked
        int linhaSelecionada = tableVeiculos.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha na tabela de Veículos para excluir.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int codigo = (int) tableVeiculos.getValueAt(linhaSelecionada, 0);
        TelaEditar editarVeiculo = new TelaEditar(codigo);
        editarVeiculo.setVisible(true);
        desabilitarBtn();
        tableVeiculos.clearSelection();


        dispose();        dispose();    }//GEN-LAST:event_menuAtualizarMouseClicked

    private void menuExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuExcluirMouseClicked
        int linhaSelecionada = tableVeiculos.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha na tabela de Veículos para excluir.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        DefaultTableModel dtm = (DefaultTableModel) tableVeiculos.getModel();
        int confirmarRemocao = JOptionPane.showConfirmDialog(rootPane, "Realmente deseja remover este Veículo", "Confirmar Remoção", JOptionPane.YES_NO_OPTION);

        if (confirmarRemocao == JOptionPane.YES_OPTION) {
            Veiculo.removerVeiculo(linhaSelecionada);
            dtm.removeRow(linhaSelecionada);
            JOptionPane.showMessageDialog(rootPane, "Veículo removido com sucesso!!!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
            habilitarBtn();
        }
        tableVeiculos.clearSelection();


    }//GEN-LAST:event_menuExcluirMouseClicked

    private void comboBoxListarVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxListarVeiculosActionPerformed
        updateTable();
    }//GEN-LAST:event_comboBoxListarVeiculosActionPerformed

    private void menuVenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuVenderMouseClicked
        int linhaSelecionada = tableVeiculos.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha na tabela de Veículos para excluir.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int codigo = (int) tableVeiculos.getValueAt(linhaSelecionada, 0);
        TelaVenda venda = new TelaVenda(codigo);
        venda.setVisible(true);
        habilitarBtn();
    }//GEN-LAST:event_menuVenderMouseClicked

    private void menuRelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRelatorioMouseClicked
        if (tableVeiculos.getSelectedRow() > -1) {
            JOptionPane.showMessageDialog(rootPane, "Não é possível acessar Relatório com um veículo selecionado.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (Veiculo.getList().size() == 0 && VendaVeiculo.getListVendas().size() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Cadastre ou venda um veículo para acessar relatório", "Erro", JOptionPane.ERROR_MESSAGE);
            menuRelatorio.setEnabled(false);
            return;
        }

        TelaRelatorio relatorio = new TelaRelatorio();
        relatorio.setVisible(true);
        dispose();


    }//GEN-LAST:event_menuRelatorioMouseClicked

    private void tableVeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableVeiculosMouseClicked
        if (tableVeiculos.getSelectedRow() != -1) {
            desabilitarBtn();
        }
    }//GEN-LAST:event_tableVeiculosMouseClicked

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        int confirmarRemocao = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja sair do programa?", "Encerrar  Programa", JOptionPane.YES_NO_OPTION);

        if (confirmarRemocao == JOptionPane.YES_OPTION) {
            System.exit(0);
        }

    }//GEN-LAST:event_btnSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnSair;
    private javax.swing.JComboBox<String> comboBoxListarVeiculos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuAtualizar;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenu menuExcluir;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenu menuVender;
    private javax.swing.JTable tableVeiculos;
    // End of variables declaration//GEN-END:variables
}
