/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Questao1;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carlo
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        this.setLocationRelativeTo(null);
        menuEditar.setEnabled(false);
        menuExcluir.setEnabled(false);
        menuDeslececionar.setEnabled(false);
        updateTable();
    }

    public void habilitarBtn() {
        menuCadastrar.setEnabled(true);
        menuEditar.setEnabled(false);
        menuExcluir.setEnabled(false);
        menuDeslececionar.setEnabled(false);
    }

    public void desabilitarBtn() {
        menuCadastrar.setEnabled(false);
        menuEditar.setEnabled(true);
        menuExcluir.setEnabled(true);
        menuDeslececionar.setEnabled(true);

    }

    public void updateTable() {
        DefaultTableModel dtmTableVeiculo = (DefaultTableModel) tableContatos.getModel();
        dtmTableVeiculo.setRowCount(0);

        for (int i = 0; i < Contatos.getLista().size(); i++) {

            habilitarBtn();
            dtmTableVeiculo.addRow(new Object[]{
                Contatos.getLista().get(i).getId(),
                Contatos.getLista().get(i).getNome(),
                Contatos.getLista().get(i).getEmail(),
                Contatos.getLista().get(i).getTelefone()

            });
        }

        dtmTableVeiculo.fireTableDataChanged();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableContatos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastrar = new javax.swing.JMenu();
        menuEditar = new javax.swing.JMenu();
        menuExcluir = new javax.swing.JMenu();
        menuDeslececionar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableContatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "EMAIL", "TELEFONE"
            }
        ));
        tableContatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableContatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableContatos);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setText("Bem Vindo(a) a ContatoSystem");

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuBar1.setInheritsPopupMenu(true);
        jMenuBar1.setMargin(new java.awt.Insets(10, 40, 10, 100));

        menuCadastrar.setText("Cadastrar");
        menuCadastrar.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        menuCadastrar.setMargin(new java.awt.Insets(3, 6, 3, 40));
        menuCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCadastrarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuCadastrar);

        menuEditar.setText("Editar");
        menuEditar.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        menuEditar.setMargin(new java.awt.Insets(3, 6, 3, 40));
        menuEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEditarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuEditar);

        menuExcluir.setText("Excluir");
        menuExcluir.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        menuExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuExcluirMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuExcluir);

        menuDeslececionar.setText("Deslecelecionar Linha");
        menuDeslececionar.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        menuDeslececionar.setMargin(new java.awt.Insets(10, 40, 10, 6));
        menuDeslececionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDeslececionarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuDeslececionar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCadastrarMouseClicked
        if (tableContatos.getSelectedRow() > -1) {
            JOptionPane.showMessageDialog(rootPane, "Não é possível Cadastrar um novo Contato com linha selecionada.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        new TelaCadastrar().setVisible(true);
        dispose();
        habilitarBtn();

    }//GEN-LAST:event_menuCadastrarMouseClicked

    private void menuEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEditarMouseClicked
        int linhaSelecionada = tableContatos.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha na tabela de um Contato para excluir.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int codigo = (int) tableContatos.getValueAt(linhaSelecionada, 0);
        TelaEditar editarVeiculo = new TelaEditar(codigo);
        editarVeiculo.setVisible(true);
        tableContatos.clearSelection();
        dispose();
        desabilitarBtn();
    }//GEN-LAST:event_menuEditarMouseClicked

    private void menuExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuExcluirMouseClicked
        int linhaSelecionada = tableContatos.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha na tabela de Contato para excluir.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        DefaultTableModel dtm = (DefaultTableModel) tableContatos.getModel();
        int confirmarRemocao = JOptionPane.showConfirmDialog(rootPane, "Realmente deseja remover este Contato?", "Confirmar Remoção", JOptionPane.YES_NO_OPTION);

        if (confirmarRemocao == JOptionPane.YES_OPTION) {
            Contatos.removerContatosTable(linhaSelecionada);
            dtm.removeRow(linhaSelecionada);
            JOptionPane.showMessageDialog(rootPane, "Contato removido com sucesso!!!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
        }
        tableContatos.clearSelection();
        habilitarBtn();

    }//GEN-LAST:event_menuExcluirMouseClicked

    private void tableContatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableContatosMouseClicked
        if (tableContatos.getSelectedRow() != -1) {
            desabilitarBtn();
        }    }//GEN-LAST:event_tableContatosMouseClicked

    private void menuDeslececionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDeslececionarMouseClicked
        tableContatos.clearSelection();

    }//GEN-LAST:event_menuDeslececionarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenu menuDeslececionar;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenu menuExcluir;
    private javax.swing.JTable tableContatos;
    // End of variables declaration//GEN-END:variables
}
